[build]
  command = "npm run build"
  publish = ".next"

# These headers ensure proper caching for Next.js assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# This plugin helps optimize Next.js deployments on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"